# Import all forms
from .fields import *
from .teams import *
from .gametypes import *
from .editor import *
from .accounts import *
from .tournaments import *
from .managers import *
from .swap import *
from .website_settings import *
