# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='name',
            field=models.CharField(default='', max_length=2048),
            preserve_default=False,
        ),
    ]
