# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 21:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_field_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='tournament',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservations.Tournament'),
        ),
    ]
