# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 21:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_auto_20151215_1321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='game_type',
            new_name='gametype',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='time_slot',
            new_name='timeslot',
        ),
    ]
