# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 21:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_reservationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='location',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='reservations.Field'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
