# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 18:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_auto_20151228_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='gametype',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='reservations.GameType'),
            preserve_default=False,
        ),
    ]
