# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_reservation_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
