# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-14 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_tournament_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='tournament',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='active',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='gametype',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='location',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='team',
        ),
        migrations.AddField(
            model_name='tournament',
            name='locations',
            field=models.ManyToManyField(to='reservations.Field'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='name',
            field=models.CharField(default=None, max_length=2048),
            preserve_default=False,
        ),
    ]
