# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-15 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0011_websitesettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='websitesettings',
            options={'verbose_name': 'website settings', 'verbose_name_plural': 'website settings'},
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='description',
            field=models.CharField(default='TEst', max_length=2048),
            preserve_default=False,
        ),
    ]
