# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-15 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0012_auto_20160115_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitesettings',
            name='key',
            field=models.CharField(max_length=2048, unique=True),
        ),
    ]
