# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-19 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0013_auto_20160115_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitesettings',
            name='value',
            field=models.CharField(max_length=2048),
        ),
    ]
