# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-19 17:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0014_auto_20160119_0909'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WebsiteSettings',
            new_name='WebsiteSetting',
        ),
        migrations.AlterModelOptions(
            name='websitesetting',
            options={},
        ),
    ]
