# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-26 22:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0016_teamprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamprofile',
            name='id',
        ),
        migrations.AddField(
            model_name='tournament',
            name='gametype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reservations.GameType'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teamprofile',
            name='description',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='teamprofile',
            name='team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
