# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-28 21:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0017_auto_20160126_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='gametype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservations.GameType'),
        ),
    ]
