# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-29 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0018_auto_20160128_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gametype',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
