# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-31 05:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0018_auto_20160128_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_number', models.IntegerField()),
                ('game_opponent', models.CharField(max_length=2048)),
                ('date', models.DateField()),
                ('approved', models.BooleanField()),
                ('team', models.CharField(max_length=2048)),
                ('location', models.CharField(max_length=2048)),
                ('gametype', models.CharField(max_length=2048)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
    ]
