# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-31 05:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0019_archivedreservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='active',
        ),
    ]
