# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-29 18:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0019_auto_20160129_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='active',
        ),
        migrations.RemoveField(
            model_name='gametype',
            name='active',
        ),
    ]
