# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-01 17:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0020_auto_20160129_1003'),
        ('reservations', '0020_remove_reservation_active'),
    ]

    operations = [
    ]
