# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-09 17:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0022_reservation_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='active',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='active',
        ),
    ]
