# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-02 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0023_auto_20160209_0921'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='field',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='gametype',
            options={'ordering': ['type']},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['date', 'location__name', 'timeslot__start_time']},
        ),
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ['start_time']},
        ),
        migrations.AlterModelOptions(
            name='tournament',
            options={'ordering': ['start_date']},
        ),
        migrations.AddField(
            model_name='field',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gametype',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
