# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-03 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0024_auto_20160401_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='overlap',
            field=models.ManyToManyField(related_name='_timeslot_overlap_+', to='reservations.TimeSlot'),
        ),
    ]
