# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-03 21:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0025_timeslot_overlap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='gametype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservations.GameType'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservations.Field'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='timeslot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservations.TimeSlot'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='gametype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reservations.GameType'),
        ),
    ]
