# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0026_auto_20160403_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedreservation',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
