# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 18:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


from datetime import timezone
utc = timezone.utc


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0027_archivedreservation_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationtoken',
            name='hold_date',
            field=models.DateField(default=datetime.datetime(2016, 8, 3, 18, 14, 26, 485769, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
