# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0028_reservationtoken_hold_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationtoken',
            name='hold_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
