# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-04 17:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0031_managerprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='managerprofile',
            old_name='manager',
            new_name='user',
        ),
    ]
