# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-26 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0032_auto_20160804_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedTournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2048)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('gametype', models.CharField(max_length=2048)),
                ('locations', models.TextField()),
            ],
        ),
    ]
