# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2022-05-29 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0033_archivedtournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='gender',
            field=models.CharField(choices=[('boys', 'boys'), ('girls', 'girls')], default='boys', max_length=5),
        ),
        migrations.AddField(
            model_name='teamprofile',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teamprofile',
            name='gender',
            field=models.CharField(choices=[('boys', 'boys'), ('girls', 'girls')], default='boys', max_length=5),
        ),
    ]
