# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2022-05-30 02:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservations', '0034_auto_20220528_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedreservation',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='archivedreservation',
            name='gender',
            field=models.CharField(choices=[('boys', 'boys'), ('girls', 'girls')], default='boys', max_length=5),
        ),
        migrations.AddField(
            model_name='gametype',
            name='teams',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
