# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2022-05-30 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0035_auto_20220529_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivedreservation',
            name='age',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='age',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='teamprofile',
            name='age',
            field=models.CharField(max_length=10),
        ),
    ]
